export const config = {
  title: "Create Next App",
  short_name: "Next App",
  description: "Generated by create next app",
  url: "",

  favicon: { src: "/favicon.icon", sizes: "any", type: "image/x-icon" },
};
